
version: 2

models:
  - name: dim_cities
    description: "Dimension table for cities"
    columns:
      - name: city_id
        description: "Unique identifier for city"
        tests:
          - unique
          - not_null
      - name: city_name
        description: "Name of the city"
        tests:
          - not_null

  - name: dim_time
    description: "Dimension table for time attributes"
    columns:
      - name: time_id
        description: "Unique identifier for time"
        tests:
          - unique
          - not_null

  - name: fact_weather
    description: "Fact table containing weather measurements"
    columns:
      - name: weather_id
        description: "Unique identifier for weather record"
        tests:
          - unique
          - not_null
      
      - name: city_id
        description: "Foreign key to dim_cities"
        tests:
          - not_null
          - relationships:
              to: ref('dim_cities')
              field: city_id
              
      - name: time_id
        description: "Foreign key to dim_time"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id

      - name: temperature
        description: "Temperature in Celsius"
        tests:
          - not_null

      - name: humidity
        description: "Humidity percentage"
        tests:
          - not_null
